### ISSUE TITLE
Activity app flagged for SQL Injection by ModSecurity rules

### ISSUE THREAD

**Issue by adoucette** [nextcloud/activity#396]
The official NextCloud Activity app triggers the ModSecurity web application firewall to think that a possible SQL Injection is being attempted. This can cause the activities app to return 403 error, and can cause users to be auto-banned from servers by ModSecurity.
I've seen this on a couple different nextcloud installs on a couple different shared hosting companies.

See forum post here:
https://help.nextcloud.com/t/activities-returns-error/6530/10?u=adoucette

Here is output from ModSec log:
`[client 123.456.123.214] ModSecurity: [file "/etc/httpd/conf/modsecurity.d/rules/comodo/22_SQL_SQLi.conf"] [line "17"] [id "211540"] [rev "12"] [msg "COMODO WAF: Blind SQL Injection Attack||mynextcloudwebsite.com|F|2"] [data "Matched Data: object_type found within ARGS_NAMES:object_type: object_type"] [severity "CRITICAL"] [tag "CWAF"] [tag "SQLi"] Access denied with code 403 (phase 2). Pattern match "(?i:\\\\b(?:t(?:able_name\\\\b|extpos[^a-zA-Z0-9_]{1,}\\\\()|(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|(?:filegroup|o ..." at ARGS_NAMES:object_type. [hostname "mynextcloudwebsite.com"] [uri "/ocs/v2.php/apps/activity]`

Nextcloud 16.0.5 and Activity 2.9.1

**Comment by nickvergessen** [comment]
The either reconfigure your ModSecurity or disable it.
Blocking all requests with the word "object_type" is not really a solution 🤷

**Comment by adoucette** [comment]
The ModSec rule is a RegEx that looks for the following, not just for the word object_type
`SecMarker BASE_CHECK_SQLI
SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|XML:/*|!ARGS:/body/|!ARGS:/content/|!ARGS:customized|!ARGS:desc|!ARGS:/description/|!ARGS:/message/|!ARGS_POST:object_id|!ARGS:/password/|!ARGS:Post|!ARGS:text|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|!ARGS:sql_query "(?i:\b(?:t(?:able_name\b|extpos[^a-zA-Z0-9_]{1,}\()|(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|(?:filegroup|object|(?:process|tabl)e)s))|user_(?:group|password|(?:ind_column|tab(?:_column|le)|user|(?:constrain|objec)t)s)|xtype[^a-zA-Z0-9_]{1,}\bchar)\b)|(?:\b(?:(?:instr|locate)[^a-zA-Z0-9_]{1,}\(|(?:attnotnull|c(?:harindex|onstraint_type)|m(?:sys(?:column|object|relationship|(?:ac|queri)e)s|ysql\.(db|user))|s(?:elect\b.{0,40}\b(?:ascii|substring|users{0,1})|ys\.(?:all_tables|tab|user_(?:c(?:atalog|onstraints)|(?:object|t(?:ab(?:_column|le)|rigger)|view)s)))|waitfor\b[^a-zA-Z0-9_]{0,}?\bdelay)\b)|@@spid\b))" \
	"id:211540,msg:'COMODO WAF: Blind SQL Injection Attack||%{tx.domain}|%{tx.mode}|2',phase:2,capture,block,setvar:'tx.sqli_points=+%{tx.points_limit4}',setvar:'tx.points=+%{tx.points_limit4}',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',ctl:'auditLogParts=+E',t:'none',t:'urlDecodeUni',rev:5,severity:2"
`

**Comment by nickvergessen** [comment]
Well, adjust the regex and remove `object_(?:id|(?:nam|typ)e)|` from it and it should work just fine :)

**Comment by adoucette** [comment]
Right, and of course I've fixed it on my installs.
The reason I submitted the issue here is that others are likely to have same - and this was from a clean install of NextCloud and Activity - so it may be helpful to proactively address it to prevent others from having same problem.

**Comment by adoucette** [comment]
By the way - I think we all REALLY appreciate the work that you and the NextCloud team have done to provide this software.

**Comment by nickvergessen** [comment]
> Right, and of course I've fixed it on my installs.
The reason I submitted the issue here is that others are likely to have same - and this was from a clean install of NextCloud and Activity - so it may be helpful to proactively address it to prevent others from having same problem.

The problem is, changing that would basically break all existing clients that use this feature already :disappointed:

**Comment by deajan** [comment]
For whoever might find this useful:
Still happens with NC 19.0.2, and comodo cfaw rules v1.231

Solution is to add this config to your virtualhost `SecRuleRemoveById 211540`.
Example of my config:
```
        <IfModule mod_security2.c>
                # Increase upload limit from 128M to 5G
                SecRequestBodyLimit 5368709120
                SecRequestBodyNoFilesLimit 5368709120
                SecRequestBodyLimitAction ProcessPartial
                SecResponseBodyLimitAction ProcessPartial
                SecRequestBodyAccess On

                # https://github.com/nextcloud/activity/issues/396
                SecRuleRemoveById 211540

                # err message = ModSecurity: Audit log: Failed to unlock global mutex: Inval$
                SecAuditLogStorageDir /var/log/httpd/audit
                SecAuditLogType Concurrent
                SecAuditLogDirMode 0777
                SecAuditLogFileMode 0550
        </IfModule>
```
